# Generated by Django 5.0.6 on 2024-05-30 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemistApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chemistApi.supplier'),
        ),
    ]
