# Generated by Django 5.0.6 on 2024-05-29 07:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemistApi', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='batch_no',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='quantity',
        ),
        migrations.AddField(
            model_name='medicine',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('quantity', models.PositiveBigIntegerField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='chemistApi.medicine')),
            ],
        ),
    ]