# Generated by Django 5.0.6 on 2024-06-06 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemistApi', '0003_remove_sale_customer_name_medicine_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='stock',
        ),
    ]
